export const QUERY_KEYS = {
  LOCATIONS: "locations",
  CATEGORIES: "categories",
  ADMIN_RENTS: "admin-rents",
  ADMIN_CATEGORIES: "admin-categories",
  ADMIN_LOCATIONS: "admin-locations",
  ADMIN_RENT_BY_ID: "admin-rent-by-id",
  ADMIN_CATEGORY_BY_ID: "admin-category-by-id",
  ADMIN_LOCATION_BY_ID: "admin-location-by-id",
  RECOMMENDED_RENTS: "rents-recommended",
  RENT_LIST: "rent-list",
  RENT_BY_ID: "rent-by-id",
  RENT_DETAIL_REVIEWS: "rent-detail-reviews",
  RESERVATIONS: "reservations",
  ADMİN_RESERVATIONS: "admin-reservations",
  ADMIN_REVIEWS: "admin-reviews",
};
